name: Israel Montero
description: Entre servidores y terminales Linux, camino del lado oscuro
meta_description: "linux, servers, sysadmin, bofh, debian, centos, suse, opensuse, redhat, fedora, ubuntu"

#Social
email:          'israelmgo@gmail.com'
twitter:        'israelmgo'
github:         'israelmgo'
linkedin:       'israelmgo'
gplus:          '+IsraelMontero'

markdown: kramdown
highlighter: true
logo: false
paginate: 15
timezone: Europe/Madrid
future:   true
baseurl: '/'
domain_name: 'http://yourblog-domain.com'

# Details for the RSS feed generator
url:            'http://localhost:4000'
author:         'Israel Montero'
