title:            "Israelmgo"
tagline:          Entre terminales y logs.
description:      ""
logo:             site-logo.jpg
disqus_shortname: israelmgogithubio
# Comment out url when working locally to resolve base urls correctly
url:              http://israelmgo.github.io
# url:              http://localhost:4000

# Owner/author information
owner:
  name:           Israelmgo
  avatar:         bio-photo-200x200.png
  bio:            "Java & Python programmer with big data"
  email:          israelmgo@gmail.com
  twitter:        israelmgo
  github:         israelmgo
  instagram:      israelmgo
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    "https://plus.google.com/+IsraelMontero"

google_analytics: 
google_verify:
bing_verify:
alexa_verify:

future:      true
lsi:         false
pygments:    true
markdown:    kramdown
# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:year/:month/:day/:title.html

# Internal pages/posts to include in top navigation
navigation:
  - title: Acerca
    url: /about.html
  - title: Posts
    url: /articles
  - title: Etiquetas
    url: /tags
  - title: Enlaces
    url: /links

# Related Links displayed in links page
links:
  - title: Big Data is Something
    desc: Data Warehouse,Teradata, SQL, ETL, Abinitio，Hadoop, Java and 管理
    url: http://hi.baidu.com/wzcyc

projects:
  - title: Jekyll Blur
    desc: A Beatiful Responsive Jekyll Theme
    url: https://github.com/haoch/jekyll-blur
    date: December 2013

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: [smart]

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "mademistakes.sublime-project", "mademistakes.sublime-workspace", "codekit-config.json", "Gemfile", "Gemfile.lock", "README.md", "node_modules", "Gruntfile.js", "package.json"]
