title: DAS.R00T
description: "Entre Servidores y Terminales Gnu\Linux, camino del lado oscuro."
url: http://israelmgo.github.io
base_url: /
permalink: /:year/:month/:title/
timezone: Europe/Madrid

markdown: kramdown
relative_permalinks: true
highlighter: pygments

email: israelmgo@gmail.com
disqus: israelmgogithubio

exclude: [".rvmrc", ".rbenv-version", "README", "Rakefile", "changelog.md", "sass_converter.rb", "Gemfile", "Gemfile.lock", ".tm_properties", "config.rb", "sass", "CNAME", "Procfile","_site"]
toplinks: ['about', 'archivo', 'contacto']

gems:
  - jekyll-sitemap
